title: "Pilz-Chronik - Bonusseite"
theme: minima

url: "https://pilzchronik.github.io"
baseurl: "/bonusseite"

lang: de
timezone: Europe/Vienna

minima:
  date_format: "%-d. %B %Y"

# Seiten, die oben im MenÃ¼ angezeigt werden sollen
header_pages:
  - index.md
  - dna-herkunft.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
