title: "Pilz-Chronik - Bonusseite"
theme: minima

url: "https://pilzchronik.github.io"
baseurl: "/bonusseite"

lang: de
timezone: Europe/Vienna

minima:
  date_format: "%-d. %B %Y"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
